apiVersion: apps/v1
kind: Deployment

metadata:
  name: train-record-api

spec:
  replicas: 12
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: train-record-api
  template:
    metadata:
      labels:
        app: train-record-api
    spec:
      containers:
        - name: train-record-api
          image: gustavom96/train-record:0bece08
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-dotnet-configmap
            - secretRef:
                name: app-dotnet-secrets
          # env:
          #   - name: APP
          #     valuefrom:
          #       configmapkeyref:
          #         name: app-ts
          #         key: app-name
          #   - name: API_KEY
          #     valuefrom:
          #       secretkeyref:
          #         name: app-ts-secrets
          #         key: api-key
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /Startup
              port: 8080
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 15
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /Liveness #/Readiness when the DB will be healthy, replace it
              port: 8080
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 5
            initialDelaySeconds: 2
          livenessProbe:
            httpGet:
              path: /Liveness
              port: 8080
            failureThreshold: 2
            successThreshold: 1
            periodSeconds: 5
            initialDelaySeconds: 2
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
